#!/usr/bin/env bash
#Redirection

apt-get update -y
apt-get install nginx -y
sudo ufw allow 'NGINX HTTP'
echo "Hello World!" > sudo /var/www/html/index.nginx-debian.html
sed -i "37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx restart