#!/usr/bin/env bash
# Not found page 404

apt-get update -y
apt-get install inginx -y
sudo ufw allow 22
sudo ufw allow 80
sudo ufw enable

echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/custom_404.html
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/listen 80 default_server/a error_page 404 /custom_404.html; location = /custom_404.html {root /usr/share/nginx/html;\n internal;}' /etc/nginx/sites-available/default
sudo service nginx restart
