#!/usr/bin/env bash
# manage my processes

PID_FILE="/var/run/my_process.pid"
case "$1" in
	start)
		./manage_my_process &
		echo $! > $PID_FILE
		echo "manage_my_process started"
		;;
	stop)
		kill "$(cat $PID_FILE)"
		rm $PID_FILE
		echo "manage_my_process stopped"
		;;
	restart)
		kill "$(cat $PID_FILE)"
		rm $PID_FILE
		./manage_my_process &
		echo $! > $PID_FILE
		echo "manage_my_process restarted"
		;;

		*)
			echo "Usage: manage_my_process {start|stop|restart}"
esac
