#!/usr/bin/env bash
# script that displays the visitor IP along with the HTTP status code
# Ordered from the greatest to the lowest number of occurrence
# $1 - visitor id
# #9 - HTTP status code

logfile="apache-access.log"
awk '{print $1, $9}' "$logfile" | sort | uniq -c | sort -rn
