#!/usr/bin/env bash
# This script loops from 1 to 10
# but dispays "good luck" the 4th time
# and dispays "back luck" the 8th time
# the rest it displays "best school"

str=1
while [ $str -le 10 ]
do
	if [ $str -eq 4 ]; then
		echo "bad luck"

	elif [ $str -eq 8 ]; then
		echo "good luck"

	else
		echo "Best School"

	fi
	((str++))
done
